### ISSUE TITLE
OPAM package does not install profiler executables

### ISSUE THREAD

**Issue by mmottl** [janestreet/core_profiler#1]
It seems that the OPAM package does not install the required tools to analyze profiler output.

**Comment by ghost** [comment]
It does, they are named `core-profiler-tool` and `core-profiler-dump-metrics`

**Comment by mmottl** [comment]
I see.  Maybe the Wiki could be updated to reflect the names used in the OPAM package, which will likely be the way most people are going to install the profiler.

**Comment by ghost** [comment]
Indeed, I updated the wiki, thanks!
